// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nVkxAORju5N6BFAqm5SLd-jikkQZvRM',
    appId: '1:156511535373:web:082346610ab3c571fc7044',
    messagingSenderId: '156511535373',
    projectId: 'itas274-final-7099d',
    authDomain: 'itas274-final-7099d.firebaseapp.com',
    storageBucket: 'itas274-final-7099d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq6a2f_gIJiRt72MMK-H-xQOcCZHc_ERQ',
    appId: '1:156511535373:android:5fc7e741c037a8e1fc7044',
    messagingSenderId: '156511535373',
    projectId: 'itas274-final-7099d',
    storageBucket: 'itas274-final-7099d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7K8fYsFm9dlGlIECA737k41H710qGTQo',
    appId: '1:156511535373:ios:dae61d1b2dc3eca7fc7044',
    messagingSenderId: '156511535373',
    projectId: 'itas274-final-7099d',
    storageBucket: 'itas274-final-7099d.appspot.com',
    iosClientId: '156511535373-vdc0iuicnqqlg3eopmqjre1ppobjmbl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7K8fYsFm9dlGlIECA737k41H710qGTQo',
    appId: '1:156511535373:ios:dae61d1b2dc3eca7fc7044',
    messagingSenderId: '156511535373',
    projectId: 'itas274-final-7099d',
    storageBucket: 'itas274-final-7099d.appspot.com',
    iosClientId: '156511535373-vdc0iuicnqqlg3eopmqjre1ppobjmbl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
